// package DAY19.06-Enum Funtionalites;

public class functionalities {

    public static void main(String[] args) {
        /*enum class give some methods which are very useful

        enum class extends ENUM(which is in java.lang package)
            1.values              1&2 are generated by compiler
            2.valuesOf(String)
            3.name()
            4.odinal()   3 and 4 only comes from ENUMS Class not 4 all methods
        */
    }
    
}
